<html>
<head>
<title>Zeus Grid, Inc.</title>
<link rel="stylesheet" href="./teststyle.css" type="text/css" />
</head>
<body>
<div class="topbar">
<?php echo "$form_name"; ?>
</div>
<div class="linkbar">
<a href="http://www.zeusgrid.com">
Top Links go here</a>
<a href="http://www.zeusgrid.com">
Second Link</a>
<a href="http://www.nolink.com">
Third link</a>
</div>
<table>
<tr><td class="sidebar" valign="top">
<a href="http://www.nolink.com">
side links go here</a><br>
<a href="http://www.nolink.com">
side link2</a><br>
</td><td class="content">
